### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by B4RD4k** [BishopFox/h2csmuggler#1]
Hi,
When trying to run the tool, getting the following error, this is normal behavior?

Is revenue impacted: [Yes / No]root@kali:~/Desktop/most_used_tools/h2csmuggler# ./h2csmuggler.py -x https://google.com --test
Traceback (most recent call last):
  File "./h2csmuggler.py", line 360, in <module>
    init()
  File "./h2csmuggler.py", line 356, in init
    main(args)
  File "./h2csmuggler.py", line 191, in main
    extra_data = get_upgrade_response(connection)
  File "./h2csmuggler.py", line 92, in get_upgrade_response
    raise RuntimeError("Not upgrading!")
RuntimeError: Not upgrading!

- Urgency: [High / Medium / Low]
- Deadline: [Date]

## Platform Affected
[ ] Dev
[ ] Preview
[ ] Production

## Steps to Reproduce
Steps to reproduce the behavior

### Additional context
OS, Desktop/Mobile, Browser, Date/Time,

**Comment by the-bumble** [comment]
Hi B4RD4K, 

Yes, that is the current failure message when an h2c upgrades was not possible. But I can see how that can be a bit confusing, I'll look into changing the output.

Thank you!

Jake

**Comment by B4RD4k** [comment]
Yep, after searching it a bit I came into that conclusion.

Kudos for the hard work!!

**Comment by the-bumble** [comment]
Just pushed a change to print an error more gracefully. Haha I agree that was a bit confusing. I appreciate it and thank you for the feedback :)

**Comment by BitnomadLive** [comment]
Hi,

I just run into another error which needs some error handling:


h2csmuggler.py -x https://lists.wordpress.org --test:
Traceback (most recent call last):
  File "/root/Tools/h2csmuggler/h2csmuggler.py", line 361, in <module>
    init()
  File "/root/Tools/h2csmuggler/h2csmuggler.py", line 357, in init
    main(args)
  File "/root/Tools/h2csmuggler/h2csmuggler.py", line 181, in main
    connection = establish_tcp_connection(proxy_url)
  File "/root/Tools/h2csmuggler/h2csmuggler.py", line 52, in establish_tcp_connection
    retSock.connect(connect_args)
  File "/usr/lib/python3.6/ssl.py", line 1109, in connect
    self._real_connect(addr, False)
  File "/usr/lib/python3.6/ssl.py", line 1096, in _real_connect
    socket.connect(self, addr)
