### ISSUE TITLE
Traceback issue

### ISSUE THREAD

**Issue by mrityuShell** [BishopFox/h2csmuggler#11]
First off, great research, like literally mindblowing, now coming to the bug!
When I am running this tool, after a couple of seconds I am getting this error :
```javascript
Traceback (most recent call last):
  File "./h2csmuggler.py", line 378, in <module>
    init()
  File "./h2csmuggler.py", line 352, in init
    p.map(scan, lines)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "./h2csmuggler.py", line 286, in scan
    connection.shutdown(socket.SHUT_RDWR)
OSError: [Errno 107] Transport endpoint is not connected
```

**Comment by Sarfu47** [comment]
Same problem
